import type { Product, Apparel, Music, Accessory } from "../types";

export const tShirts: Apparel[] = [
  {
    id: "blood-incantation-logo-tour-2022-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_logo-tour-2022-t-shirt_front.jpg",
      "blood-incantation_logo-tour-2022-t-shirt_back.jpg",
    ],
    productName: "Logo - Tour 2022",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2023, 1, 10),
  },
  {
    id: "blood-incantation-orbital-remains-tour-2022-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_orbital-remains-tour-2022-t-shirt_front.jpg",
      "blood-incantation_orbital-remains-tour-2022-t-shirt_back.jpg",
    ],
    productName: "Orbital Remains - Tour 2022",
    color: "Heather Grey",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2023, 1, 10),
  },
  {
    id: "blood-incantation-split-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: ["blood-incantation_split-t-shirt.jpg"],
    productName: "Split",
    color: "White",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2015, 8, 20),
  },
  {
    id: "blood-incantation-timewave-zero-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_timewave-zero-t-shirt_front.jpg",
      "blood-incantation_timewave-zero-t-shirt_back.jpg",
    ],
    productName: "Timewave Zero",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2022, 1, 25),
  },
  {
    id: "blood-incantation-timewave-zero-tour-2022-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_timewave-zero-tour-2022-t-shirt_front.jpg",
      "blood-incantation_timewave-zero-tour-2022-t-shirt_back.jpg",
    ],
    productName: "Timewave Zero - Tour 2022",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2022, 1, 25),
  },
  {
    id: "blood-incantation-live-vitrification-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: ["blood-incantation_live-vitrification-t-shirt.jpg"],
    productName: "Live Vitrification",
    color: "White",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2023, 8, 30),
  },
  {
    id: "blood-incantation-hidden-history-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_hidden-history-t-shirt_front.jpg",
      "blood-incantation_hidden-history-t-shirt_back.jpg",
    ],
    productName: "Hidden History",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2019, 10, 22),
  },
  {
    id: "blood-incantation-starspawn-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_starspawn-t-shirt_front.jpg",
      "blood-incantation_starspawn-t-shirt_back.jpg",
    ],
    productName: "Starspawn",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2016, 7, 13),
  },
  {
    id: "blood-incantation-hidden-species-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_hidden-species-t-shirt_front.jpg",
      "blood-incantation_hidden-species-t-shirt_back.jpg",
    ],
    productName: "Hidden Species",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2021, 5, 12),
  },
  {
    id: "blood-incantation-timewave-zero-pocket-grey-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_timewave-zero-pocket-grey-t-shirt_front.jpg",
      "blood-incantation_timewave-zero-pocket-grey-t-shirt_back.jpg",
    ],
    productName: "Timewave Zero Pocket - Grey",
    color: "Heather Grey",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2022, 1, 25),
  },
  {
    id: "blood-incantation-red-logo-t-shirt",
    category: "t-shirts",
    productType: "T-Shirt",
    imgs: [
      "blood-incantation_red-logo-t-shirt_front.jpg",
      "blood-incantation_red-logo-t-shirt_back.jpg",
    ],
    productName: "Red Logo",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 24.99,
    dateAdded: new Date(2023, 8, 30),
  },
];

export const longsleeves: Apparel[] = [
  {
    id: "blood-incantation-interdimensional-extinction-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_interdimensional-extinction-longsleeve_front.jpg",
      "blood-incantation_interdimensional-extinction-longsleeve_back.jpg",
    ],
    productName: "Interdimensional Extinction",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2015, 9, 30),
  },
  {
    id: "blood-incantation-interdimensional-extinction-logo-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_interdimensional-extinction-logo-longsleeve_front.jpg",
      "blood-incantation_interdimensional-extinction-logo-longsleeve_back.jpg",
    ],
    productName: "Interdimensional Extinction - Logo",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2015, 9, 30),
  },
  {
    id: "blood-incantation-interdimensional-pocket-tour-2022-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_interdimensional-pocket-tour-2022-longsleeve_front.jpg",
      "blood-incantation_interdimensional-pocket-tour-2022-longsleeve_back.jpg",
    ],
    productName: "Interdimensional Pocket - Tour 2022",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2023, 1, 15),
  },
  {
    id: "blood-incantation-bacteria-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_bacteria-longsleeve_front.jpg",
      "blood-incantation_bacteria-longsleeve_back.jpg",
    ],
    productName: "Bacteria",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2021, 5, 12),
  },
  {
    id: "blood-incantation-logo-grey-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_logo-grey-longsleeve_front.jpg",
      "blood-incantation_logo-grey-longsleeve_back.jpg",
    ],
    productName: "Logo - Grey",
    color: "Heather Grey",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2021, 5, 12),
  },
  {
    id: "blood-incantation-timewave-zero-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_timewave-zero-longsleeve_front.jpg",
      "blood-incantation_timewave-zero-longsleeve_back.jpg",
    ],
    productName: "Timewave Zero",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2022, 0, 2),
  },
  {
    id: "blood-incantation-timewave-zero-pocket-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_timewave-zero-pocket-longsleeve_front.jpg",
      "blood-incantation_timewave-zero-pocket-longsleeve_back.jpg",
    ],
    productName: "Timewave Zero - Pocket",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2023, 1, 10),
  },
  {
    id: "blood-incantation-starspawn-pocket-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_starspawn-pocket-longsleeve_front.jpg",
      "blood-incantation_starspawn-pocket-longsleeve_back.jpg",
    ],
    productName: "Starspawn - Pocket",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2016, 7, 13),
  },
  {
    id: "blood-incantation-hidden-history-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_hidden-history-longsleeve_front.jpg",
      "blood-incantation_hidden-history-longsleeve_back.jpg",
    ],
    productName: "Hidden History of the Human Race",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2019, 10, 22),
  },
  {
    id: "blood-incantation-hidden-history-tour-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_hidden-history-tour-longsleeve_front.jpg",
      "blood-incantation_hidden-history-tour-longsleeve_back.jpg",
    ],
    productName: "Hidden History - Tour",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2019, 10, 22),
  },
  {
    id: "blood-incantation-hidden-species-longsleeve",
    category: "longsleeves",
    productType: "Longsleeve",
    imgs: [
      "blood-incantation_hidden-species-longsleeve_front.jpg",
      "blood-incantation_hidden-species-longsleeve_back.jpg",
    ],
    productName: "Hidden Species",
    color: "Black",
    manufacturer: "Gildan",
    material: "100% Cotton",
    price: 34.99,
    dateAdded: new Date(2021, 5, 12),
  },
];

export const hoodies: Apparel[] = [
  {
    id: "blood-incantation-hidden-history-hoodie",
    category: "hoodies",
    productType: "Hoodie",
    imgs: [
      "blood-incantation_hidden-history-hoodie_front.jpg",
      "blood-incantation_hidden-history-hoodie_back.jpg",
    ],
    productName: "Hidden History of the Human Race",
    color: "Black",
    manufacturer: "Gildan",
    material: "50% Cotton / 50% Polyester",
    price: 29.99,
    dateAdded: new Date(2019, 10, 22),
  },
];

export const vinyl: Music[] = [
  {
    id: "blood-incantation-interdimensional-extinction-lp",
    category: "vinyl",
    productType: "LP",
    imgs: [
      "blood-incantation_interdimensional-extinction-lp_1.jpg",
      "blood-incantation_interdimensional-extinction-lp_2.jpg",
      "blood-incantation_interdimensional-extinction-lp_3.jpg",
    ],
    productName: "Interdimensional Extinction",
    price: 21.99,
    dateAdded: new Date(2015, 7, 13),
    tracklist: [
      "The Vth Tablet (Of Enuma Elis)",
      "Obfuscating the Linear Threshold",
      "Hovering Lifeless",
      "Subterranean Aeon",
    ],
  },
  {
    id: "blood-incantation-starspawn-lp",
    category: "vinyl",
    productType: "LP",
    imgs: [
      "blood-incantation_starspawn-lp_1.jpg",
      "blood-incantation_starspawn-lp_2.jpg",
      "blood-incantation_starspawn-lp_3.jpg",
      "blood-incantation_starspawn-lp_4.jpg",
      "blood-incantation_starspawn-lp_5.jpg",
    ],
    productName: "Starspawn",
    price: 21.99,
    dateAdded: new Date(2016, 7, 13),
    tracklist: [
      "Vitrification of Blood (Part I)",
      "Chaoplasm",
      "Hidden Species (Vitrification of Blood (Part II))",
      "Meticulous Soul Devourment",
      "Starspawn",
    ],
  },
  {
    id: "blood-incantation-hidden-history-lp",
    category: "vinyl",
    productType: "LP",
    imgs: [
      "blood-incantation_hidden-history-lp_1.jpg",
      "blood-incantation_hidden-history-lp_2.jpg",
      "blood-incantation_hidden-history-lp_3.jpg",
      "blood-incantation_hidden-history-lp_4.jpg",
    ],
    productName: "Hidden History of the Human Race",
    price: 21.99,
    dateAdded: new Date(2019, 10, 22),
    tracklist: [
      "Slave Species of the Gods",
      "The Giza Power Plant",
      "Inner Paths (to Outer Space)",
      "Awakening From the Dream of Existence to the Multidimensional Nature of Our Reality (Mirror of the Soul)",
    ],
  },
  {
    id: "blood-incantation-timewave-zero-lp",
    category: "vinyl",
    productType: "LP",
    imgs: ["blood-incantation_timewave-zero-lp.jpg"],
    productName: "Timewave Zero",
    price: 21.99,
    dateAdded: new Date(2022, 0, 2),
    tracklist: ["Io", "Ea"],
  },
];

export const cds: Music[] = [
  {
    id: "blood-incantation-interdimensional-extinction-cd",
    category: "cds",
    productType: "CD",
    imgs: ["blood-incantation_interdimensional-extinction-lp_1.jpg"],
    productName: "Interdimensional Extinction",
    price: 14.99,
    dateAdded: new Date(2015, 7, 13),
    tracklist: [
      "The Vth Tablet (Of Enuma Elis)",
      "Obfuscating the Linear Threshold",
      "Hovering Lifeless",
      "Subterranean Aeon",
    ],
  },
  {
    id: "blood-incantation-starspawn-cd",
    category: "cds",
    productType: "CD",
    imgs: ["blood-incantation_starspawn-lp_1.jpg"],
    productName: "Starspawn",
    price: 14.99,
    dateAdded: new Date(2016, 7, 13),
    tracklist: [
      "Vitrification of Blood (Part I)",
      "Chaoplasm",
      "Hidden Species (Vitrification of Blood (Part II))",
      "Meticulous Soul Devourment",
      "Starspawn",
    ],
  },
  {
    id: "blood-incantation-hidden-history-cd",
    category: "cds",
    productType: "CD",
    imgs: [
      "blood-incantation_hidden-history-lp_1.jpg",
      "blood-incantation_hidden-history-cd_2.jpg",
    ],
    productName: "Hidden History of the Human Race",
    price: 15.99,
    dateAdded: new Date(2019, 10, 22),
    tracklist: [
      "Slave Species of the Gods",
      "The Giza Power Plant",
      "Inner Paths (to Outer Space)",
      "Awakening From the Dream of Existence to the Multidimensional Nature of Our Reality (Mirror of the Soul)",
    ],
  },
  {
    id: "blood-incantation-timewave-zero-cd",
    category: "cds",
    productType: "CD",
    imgs: [
      "blood-incantation_timewave-zero-lp.jpg",
      "blood-incantation_timewave-zero-cd_2.jpg",
    ],
    productName: "Timewave Zero",
    price: 18.99,
    dateAdded: new Date(2022, 0, 2),
    tracklist: ["Io", "Ea"],
  },
];

export const patches: Accessory[] = [
  {
    id: "blood-incantation-hidden-history-of-the-human-race-patch",
    category: "patches",
    productType: "Patch",
    imgs: ["blood-incantation_hidden-history-of-the-human-race-patch.jpg"],
    productName: "Hidden History of the Human Race",
    price: 12.99,
    desc: ["Sewn patch - 7.5cm wide, 10cm high."],
    dateAdded: new Date(2019, 11, 1),
  },
  {
    id: "blood-incantation-logo-white-patch",
    category: "patches",
    productType: "Patch",
    imgs: ["blood-incantation_logo-white-patch.jpg"],
    productName: "Logo - White",
    price: 12.99,
    desc: ["Embroidered patch, 10cm wide."],
    dateAdded: new Date(2018, 5, 1),
  },
  {
    id: "blood-incantation-logo-green-patch",
    category: "patches",
    productType: "Patch",
    imgs: ["blood-incantation_logo-green-patch.jpg"],
    productName: "Logo - Green",
    price: 12.99,
    desc: ["Embroidered patch, 10cm wide."],
    dateAdded: new Date(2019, 10, 15),
  },
];

export const allProducts = [
  ...tShirts,
  ...longsleeves,
  ...hoodies,
  ...vinyl,
  ...cds,
  ...patches,
];

export const apparel: Apparel[] = [...tShirts, ...longsleeves, ...hoodies];
export const music: Music[] = [...vinyl, ...cds];
export const accessories: Accessory[] = [...patches];
